### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method newInstance on channel adhara_socket_io)

### ISSUE THREAD

**Issue by CaoGiaHieu-dev** [infitio/flutter_socket_io#170]
**Describe the bug**
I run on ios device and get this error

2021-05-28 09:16:31.418797+0700 Runner[13922:108433] [VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method newInstance on channel adhara_socket_io)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      SocketIOManager.createInstance (package:adhara_socket_io/manager.dart:42:19)
<asynchronous suspension>
#2      SocketProvider._initSocket (package:flutter_background_example/socket_provider.dart:21:9)
<asynchronous suspension>

i tracking same issue was closed . But it still not working

**Comment by tiholic** [comment]
@CaoGiaHieu-dev try `flutter clean` and re-run the app.
