### ISSUE TITLE
Unable to run the example app in flutter channel master or beta (Or any flutter verion >= 1.6.3)

### ISSUE THREAD

**Issue by lhcdims** [infitio/flutter_socket_io#26]
# The following error is found in the console:

```
Launching lib\main.dart on MI 9 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Syncing files to device MI 9...
D/NetworkSecurityConfig(25663): No Network Security Config specified, using platform default
W/tobiagib.asio0(25663): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, reflection)
W/tobiagib.asio0(25663): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, reflection)
W/tobiagib.asio0(25663): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, reflection)
E/EventThread(25663): Task threw exception
E/EventThread(25663): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: EventThread
E/EventThread(25663): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/EventThread(25663): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
E/EventThread(25663): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:76)
E/EventThread(25663): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:166)
E/EventThread(25663): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
E/EventThread(25663): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
E/EventThread(25663): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
E/EventThread(25663): 	at com.infitio.adharasocketio.AdharaSocket$1.call(AdharaSocket.java:81)
E/EventThread(25663): 	at io.socket.emitter.Emitter.emit(Emitter.java:117)
E/EventThread(25663): 	at io.socket.client.Socket.access$601(Socket.java:24)
E/EventThread(25663): 	at io.socket.client.Socket$5.run(Socket.java:186)
E/EventThread(25663): 	at io.socket.thread.EventThread.exec(EventThread.java:55)
E/EventThread(25663): 	at io.socket.client.Socket.emit(Socket.java:182)
E/EventThread(25663): 	at io.socket.client.Socket.onconnect(Socket.java:389)
E/EventThread(25663): 	at io.socket.client.Socket.onpacket(Socket.java:283)
E/EventThread(25663): 	at io.socket.client.Socket.access$100(Socket.java:24)
E/EventThread(25663): 	at io.socket.client.Socket$2$2.call(Socket.java:120)
E/EventThread(25663): 	at io.socket.emitter.Emitter.emit(Emitter.java:117)
E/EventThread(25663): 	at io.socket.client.Manager.ondecoded(Manager.java:427)
E/EventThread(25663): 	at io.socket.client.Manager.access$1600(Manager.java:30)
E/EventThread(25663): 	at io.socket.client.Manager$7.call(Manager.java:403)
E/EventThread(25663): 	at io.socket.parser.IOParser$Decoder.add(IOParser.java:105)
E/EventThread(25663): 	at io.socket.client.Manager.ondata(Manager.java:419)
E/EventThread(25663): 	at io.socket.client.Manager.access$1000(Manager.java:30)
E/EventThread(25663): 	at io.socket.client.Manager$2.call(Manager.java:370)
E/EventThread(25663): 	at io.socket.emitter.Emitter.emit(Emitter.java:117)
E/EventThread(25663): 	at io.socket.engineio.client.Socket.onPacket(Socket.java:551)
E/EventThread(25663): 	at io.socket.engineio.client.Socket.access$1000(Socket.java:36)
E/EventThread(25663): 	at io.socket.engineio.client.Socket$5.call(Socket.java:335)
E/EventThread(25663): 	at io.socket.emitter.Emitter.emit(Emitter.java:117)
E/EventThread(25663): 	at io.socket.engineio.client.Transport.onPacket(Transport.java:126)
E/EventThread(25663): 	at io.socket.engineio.client.transports.Polling.access$700(Polling.java:18)
E/EventThread(25663): 	at io.socket.engineio.client.transports.Polling$2.call(Polling.java:127)
E/EventThread(25663): 	at io.socket.engineio.parser.Parser.decodePayload(Parser.java:241)
E/EventThread(25663): 	at io.socket.engineio.client.transports.Polling._onData(Polling.java:135)
E/EventThread(25663): 	at io.socket.engineio.client.transports.Polling.onData(Polling.java:102)
E/EventThread(25663): 	at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:125)
E/EventThread(25663): 	at io.socket.thread.EventThread$2.run(EventThread.java:80)
E/EventThread(25663): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/EventThread(25663): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/EventThread(25663): 	at java.lang.Thread.run(Thread.java:764)
E/AndroidRuntime(25663): FATAL EXCEPTION: EventThread
E/AndroidRuntime(25663): Process: com.tobiagib.asio01, PID: 25663
E/AndroidRuntime(25663): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: EventThread
E/AndroidRuntime(25663): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/AndroidRuntime(25663): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
E/AndroidRuntime(25663): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:76)
E/AndroidRuntime(25663): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:166)
E/AndroidRuntime(25663): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
E/AndroidRuntime(25663): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
E/AndroidRuntime(25663): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
E/AndroidRuntime(25663): 	at com.infitio.adharasocketio.AdharaSocket$1.call(AdharaSocket.java:81)
E/AndroidRuntime(25663): 	at io.socket.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime(25663): 	at io.socket.client.Socket.access$601(Socket.java:24)
E/AndroidRuntime(25663): 	at io.socket.client.Socket$5.run(Socket.java:186)
E/AndroidRuntime(25663): 	at io.socket.thread.EventThread.exec(EventThread.java:55)
E/AndroidRuntime(25663): 	at io.socket.client.Socket.emit(Socket.java:182)
E/AndroidRuntime(25663): 	at io.socket.client.Socket.onconnect(Socket.java:389)
E/AndroidRuntime(25663): 	at io.socket.client.Socket.onpacket(Socket.java:283)
E/AndroidRuntime(25663): 	at io.socket.client.Socket.access$100(Socket.java:24)
E/AndroidRuntime(25663): 	at io.socket.client.Socket$2$2.call(Socket.java:120)
E/AndroidRuntime(25663): 	at io.socket.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime(25663): 	at io.socket.client.Manager.ondecoded(Manager.java:427)
E/AndroidRuntime(25663): 	at io.socket.client.Manager.access$1600(Manager.java:30)
E/AndroidRuntime(25663): 	at io.socket.client.Manager$7.call(Manager.java:403)
E/AndroidRuntime(25663): 	at io.socket.parser.IOParser$Decoder.add(IOParser.java:105)
E/AndroidRuntime(25663): 	at io.socket.client.Manager.ondata(Manager.java:419)
E/AndroidRuntime(25663): 	at io.socket.client.Manager.access$1000(Manager.java:30)
E/AndroidRuntime(25663): 	at io.socket.client.Manager$2.call(Manager.java:370)
E/AndroidRuntime(25663): 	at io.socket.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime(25663): 	at io.socket.engineio.client.Socket.onPacket(Socket.java:551)
E/AndroidRuntime(25663): 	at io.socket.engineio.client.Socket.access$1000(Socket.java:36)
E/AndroidRuntime(25663): 	at io.socket.engineio.client.Socket$5.call(Socket.java:335)
E/AndroidRuntime(25663): 	at io.socket.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime(25663): 	at io.socket.engineio.client.Transport.onPacket(Transport.java:126)
E/AndroidRuntime(25663): 	at io.socket.engineio.client.transports.Polling.access$700(Polling.java:18)
E/AndroidRuntime(25663): 	at io.socket.engineio.client.transports.Polling$2.call(Polling.java:127)
E/AndroidRuntime(25663): 	at io.socket.engineio.parser.Parser.decodePayload(Parser.java:241)
E/AndroidRuntime(25663): 	at io.socket.engineio.client.transports.Polling._onData(Polling.java:135)
E/AndroidRuntime(25663): 	at io.socket.engineio.client.transports.Polling.onData(Polling.java:102)
E/AndroidRuntime(25663): 	at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:125)
E/AndroidRuntime(25663): 	at io.socket.thread.EventThread$2.run(EventThread.java:80)
E/AndroidRuntime(25663): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(25663): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(25663): 	at java.lang.Thread.run(Thread.java:764)
I/Process (25663): Sending signal. PID: 25663 SIG: 9
Lost connection to device.
```

# Steps to reproduce the error:

1. switch to either channel master or channel beta by:
flutter channel master
or
flutter channel beta

2. run the example adhara_socket_io app in Android device or emulator (I did not check IOS).

# Additional Information on why this error happens:

1. Pay attention to this line in the above error log:

E/EventThread(25663): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: EventThread

2. There was a change in flutter commited @2019/05/04, that:

The Android embedder is now checking that platform->Dart messages are sent from the platform thread.

Pls. take a look at here:

[Other flutter package (the image_picker) that has the same problem](https://github.com/flutter/flutter/issues/32315)

and here:

[Pls go to line 601](https://github.com/flutter/engine/commit/2c9e37c34e79475bbde7c8163eb5e56cdb9662a1)

# Current Work Around

use channel stable by the command:

flutter channel stable

**Comment by lhcdims** [comment]
Hi,

I solved the problem by replacing your AdharaSocket.java with the following codes, I wrapped the channel.invokeMethod and MethodChannel.Result in a handler:

```
package com.infitio.adharasocketio;

import android.util.Log;
import android.os.Handler;
import android.os.Looper;

import org.json.JSONArray;
import org.json.JSONObject;

import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import io.flutter.plugin.common.MethodCall;
import io.flutter.plugin.common.MethodChannel;
import io.flutter.plugin.common.MethodChannel.MethodCallHandler;
import io.flutter.plugin.common.MethodChannel.Result;
import io.flutter.plugin.common.PluginRegistry.Registrar;
import io.socket.client.IO;
import io.socket.client.Socket;
import io.socket.emitter.Emitter;


class AdharaSocket implements MethodCallHandler {

    final Socket socket;
    private final MethodChannel channel;
    private static final String TAG = "Adhara:Socket";
    private Options options;

    // MethodChannel.Result wrapper that responds on the platform thread.
    private static class MethodResultWrapper implements MethodChannel.Result {
        private MethodChannel.Result methodResult;
        private Handler handler;

        MethodResultWrapper(MethodChannel.Result result) {
            methodResult = result;
            handler = new Handler(Looper.getMainLooper());
        }

        @Override
        public void success(final Object result) {
            handler.post(
                    new Runnable() {
                        @Override
                        public void run() {
                            methodResult.success(result);
                        }
                    });
        }

        @Override
        public void error(
                final String errorCode, final String errorMessage, final Object errorDetails) {
            handler.post(
                    new Runnable() {
                        @Override
                        public void run() {
                            methodResult.error(errorCode, errorMessage, errorDetails);
                        }
                    });
        }

        @Override
        public void notImplemented() {
            handler.post(
                    new Runnable() {
                        @Override
                        public void run() {
                            methodResult.notImplemented();
                        }
                    });
        }
    }



    private void log(String message){
        if(this.options.enableLogging){
            Log.d(TAG, message);
        }
    }

    private AdharaSocket(MethodChannel channel, Options options) throws URISyntaxException {
        this.channel = channel;
        this.options = options;
        log("Connecting to... "+options.uri);
        socket = IO.socket(options.uri, this.options);
    }

    static AdharaSocket getInstance(Registrar registrar, Options options) throws URISyntaxException{
        final MethodChannel channel = new MethodChannel(registrar.messenger(), "adhara_socket_io:socket:"+String.valueOf(options.index));
        AdharaSocket _socket = new AdharaSocket(channel, options);
        channel.setMethodCallHandler(_socket);
        return _socket;
    }

    @Override
    // public void onMethodCall(MethodCall call, Result result) {
    public void onMethodCall(MethodCall call, MethodChannel.Result rawResult) {

        MethodChannel.Result result = new MethodResultWrapper(rawResult);

        switch (call.method) {
            case "connect": {
                log("Connecting....");
                socket.connect();
                result.success(null);
                break;
            }
            case "on": {
                final String eventName = call.argument("eventName");
                log("registering::"+eventName);
                socket.on(eventName, new Emitter.Listener() {

                    @Override
                    public void call(Object... args) {
                        log("Socket triggered::"+eventName);
                        final Map<String, Object> arguments = new HashMap<>();
                        arguments.put("eventName", eventName);
                        List<String> argsList = new ArrayList<>();
                        for(Object arg : args){
                            if((arg instanceof JSONObject)
                                    || (arg instanceof JSONArray)){
                                argsList.add(arg.toString());
                            }else if(arg!=null){
                                argsList.add(arg.toString());
                            }
                        }
                        arguments.put("args", argsList);
                        // channel.invokeMethod("incoming", arguments);
                        final Handler handler = new Handler(Looper.getMainLooper());
                        handler.post(new Runnable() {
                            @Override
                            public void run() {
                                channel.invokeMethod("incoming", arguments);
                            }
                        });
                    }

                });
                result.success(null);
                break;
            }
            case "off": {
                final String eventName = call.argument("eventName");
                log("un-registering:::"+eventName);
                socket.off(eventName);
                result.success(null);
                break;
            }
            case "emit": {
                final String eventName = call.argument("eventName");
                final List data = call.argument("arguments");
                log("emitting:::"+data+":::to:::"+eventName);
                Object[] array = {};
                if(data!=null){
                    array = new Object[data.size()];
                    for(int i=0; i<data.size(); i++){
                        Object datum = data.get(i);
                        System.out.println(datum);
                        System.out.println(datum.getClass());
                        if(datum instanceof Map){
                            array[i] = new JSONObject((Map)datum);
                        }else if(datum instanceof Collection){
                            array[i] = new JSONArray((Collection) datum);
                        }else{
                            array[i] = datum;
                            /*try{
                                array[i] = new JSONObject(datum.toString());
                            }catch (JSONException jse){
                                try{
                                    array[i] = new JSONArray(datum.toString());
                                }catch (JSONException jse2){
                                    array[i] = datum;
                                }
                            }*/
                        }
                    }
                }
                socket.emit(eventName, array);
                result.success(null);
                break;
            }
            case "isConnected": {
                log("connected:::");
                result.success(socket.connected());
                break;
            }
            case "disconnect": {
                log("disconnected:::");
                socket.disconnect();
                result.success(null);
                break;
            }
            default: {
                result.notImplemented();
            }
        }
    }

    public static class Options extends IO.Options {

        String uri;
        int index;
        public Boolean enableLogging = false;

        Options(int index, String uri){
            this.index = index;
            this.uri = uri;
        }

    }

}
```

Pls. forgive me that I don't know how to make a PR, and I am not sure whether the above codes are appropriate, pls. update your version if you think that this is OK.  Thank you.

**Comment by lhcdims** [comment]
After testing the solution in my own app for hours, I created a PR for your review, thank you.

**Comment by tiholic** [comment]
@lhcdims thank you. Will review and merge.

**Comment by tiholic** [comment]
Fixed released in [0.1.11](https://pub.dev/packages/adhara_socket_io/versions/0.1.11)

**Comment by lhcdims** [comment]
Thank you to accept my PR, by the way, did you update your package on:

https://pub.dev/packages/adhara_socket_io

meanwhile I'm still using my own fork version in my app.

**Comment by tiholic** [comment]
Yes, https://pub.dev/packages/adhara_socket_io/versions/0.1.11
This is the latest revision with the update
