### ISSUE TITLE
CocoaPods could not find compatible versions for pod "adhara_socket_io"

### ISSUE THREAD

**Issue by Vardiak** [infitio/flutter_socket_io#47]
**Describe the bug**
I get this error when I try to run the example project on my computer (see logs).

As I get this issue with the example project it seems to be related to my flutter setup but I don't see what I did wrong since I don't get any error when running `flutter doctor`.

**To Reproduce**
1. Clone the example project
2. Run `flutter run`

**Device details:**
 - Device: iPhone Xʀ
 - OS: iOS 12.4
 - Package Version: 0.2.0

**Relevant Logs**
```
Running "flutter pub get" in example...                             4.2s
Launching lib/main.dart on iPhone Xʀ in debug mode...
Removing obsolete reference to flutter_assets from Runner.app
Running pod install...                                              0.6s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `adhara_socket_io` from `.symlinks/plugins/adhara_socket_io/ios`

    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "adhara_socket_io":
      In Podfile:
        adhara_socket_io (from `.symlinks/plugins/adhara_socket_io/ios`)

    Specs satisfying the `adhara_socket_io (from `.symlinks/plugins/adhara_socket_io/ios`)` dependency were found, but they required a
    higher minimum deployment target.

    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:88:in `resolve'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:939:in `block in
    resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:937:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:118:in `analyze'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:398:in `analyze'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:221:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:220:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:156:in `install!'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/command/install.rb:51:in `run'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a
    platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone Xʀ.
```

**Comment by Vardiak** [comment]
I managed to fix this issue by uncommenting this line in `ios/Podfile` :

```
platform :ios, '9.0'
```

**Comment by Yaser-Altalhi** [comment]
Hello,
**I have managed to solve the problem.**

1- Delete the ios folder in your project.
(Note: we will recreate it in step 2).

2- Recreate iso folder and enable swift support.
terminal command:  
`flutter create -i swift `
or 
`flutter create -i swift -a kotlin .`
or 
`flutter create -i swift -a kotlin --org com.custom_name --project-name my_proyect .`
(Note: make sure you include the dot at the end of  the command)

After step 2 you should have:
iso/Runner/AppDelegate.swift

3- Navigate to ios/Podfile :
`platform :ios, '9.0'`
